import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios  from 'axios';
import { useState } from 'react';



export default function Home() {
  const [user, setUser] = useState(null);


const handleLogin = async () => {
  axios
  .get("api/auth/github")
  .then((res) => {
    setUser(res.data);
  })
  .catch((error) => {
    console.log(error);
  });
      }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        

        <button onClick={()=>handleLogin()}>Login</button>

       
      </main>
    </>
  )
}
